#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WhisperLang {
    Auto,
    Afrikaans,
    Amharic,
    Arabic,
    Assamese,
    Azerbaijani,
    Bashkir,
    Belarusian,
    Bengali,
    Bosnian,
    Breton,
    Bulgarian,
    Burmese,
    Catalan,
    Chinese,
    Croatian,
    Czech,
    Danish,
    Dutch,
    English,
    Estonian,
    Faroese,
    Finnish,
    French,
    Galician,
    Georgian,
    German,
    Greek,
    Gujarati,
    HaitianCreole,
    Hausa,
    Hawaiian,
    Hebrew,
    Hindi,
    Hungarian,
    Icelandic,
    Indonesian,
    Italian,
    Japanese,
    Javanese,
    Kannada,
    Kazakh,
    Khmer,
    Korean,
    Lao,
    Latin,
    Latvian,
    Lingala,
    Lithuanian,
    Luxembourgish,
    Macedonian,
    Malagasy,
    Malay,
    Malayalam,
    Maltese,
    Maori,
    Marathi,
    Mongolian,
    Nepali,
    Norwegian,
    Nynorsk,
    Occitan,
    Pashto,
    Persian,
    Polish,
    Portuguese,
    Punjabi,
    Romanian,
    Russian,
    Sanskrit,
    Serbian,
    Shona,
    Sindhi,
    Sinhala,
    Slovak,
    Slovenian,
    Somali,
    Spanish,
    Sundanese,
    Swahili,
    Swedish,
    Tagalog,
    Tajik,
    Tamil,
    Tatar,
    Telugu,
    Thai,
    Tibetan,
    Turkish,
    Turkmen,
    Ukrainian,
    Urdu,
    Uzbek,
    Vietnamese,
    Welsh,
    Yiddish,
    Yoruba,
}

impl ToString for WhisperLang {
    fn to_string(&self) -> String {
        match self {
            WhisperLang::Auto => "auto".to_string(),
            WhisperLang::Afrikaans => "af".to_string(),
            WhisperLang::Amharic => "am".to_string(),
            WhisperLang::Arabic => "ar".to_string(),
            WhisperLang::Assamese => "as".to_string(),
            WhisperLang::Azerbaijani => "az".to_string(),
            WhisperLang::Bashkir => "ba".to_string(),
            WhisperLang::Belarusian => "be".to_string(),
            WhisperLang::Bengali => "bn".to_string(),
            WhisperLang::Bosnian => "bs".to_string(),
            WhisperLang::Breton => "br".to_string(),
            WhisperLang::Bulgarian => "bg".to_string(),
            WhisperLang::Burmese => "my".to_string(),
            WhisperLang::Catalan => "ca".to_string(),
            WhisperLang::Chinese => "zh".to_string(),
            WhisperLang::Croatian => "hr".to_string(),
            WhisperLang::Czech => "cs".to_string(),
            WhisperLang::Danish => "da".to_string(),
            WhisperLang::Dutch => "nl".to_string(),
            WhisperLang::English => "en".to_string(),
            WhisperLang::Estonian => "et".to_string(),
            WhisperLang::Faroese => "fo".to_string(),
            WhisperLang::Finnish => "fi".to_string(),
            WhisperLang::French => "fr".to_string(),
            WhisperLang::Galician => "gl".to_string(),
            WhisperLang::Georgian => "ka".to_string(),
            WhisperLang::German => "de".to_string(),
            WhisperLang::Greek => "el".to_string(),
            WhisperLang::Gujarati => "gu".to_string(),
            WhisperLang::HaitianCreole => "ht".to_string(),
            WhisperLang::Hausa => "ha".to_string(),
            WhisperLang::Hawaiian => "haw".to_string(),
            WhisperLang::Hebrew => "he".to_string(),
            WhisperLang::Hindi => "hi".to_string(),
            WhisperLang::Hungarian => "hu".to_string(),
            WhisperLang::Icelandic => "is".to_string(),
            WhisperLang::Indonesian => "id".to_string(),
            WhisperLang::Italian => "it".to_string(),
            WhisperLang::Japanese => "ja".to_string(),
            WhisperLang::Javanese => "jw".to_string(),
            WhisperLang::Kannada => "kn".to_string(),
            WhisperLang::Kazakh => "kk".to_string(),
            WhisperLang::Khmer => "km".to_string(),
            WhisperLang::Korean => "ko".to_string(),
            WhisperLang::Lao => "lo".to_string(),
            WhisperLang::Latin => "la".to_string(),
            WhisperLang::Latvian => "lv".to_string(),
            WhisperLang::Lingala => "ln".to_string(),
            WhisperLang::Lithuanian => "lt".to_string(),
            WhisperLang::Luxembourgish => "lb".to_string(),
            WhisperLang::Macedonian => "mk".to_string(),
            WhisperLang::Malagasy => "mg".to_string(),
            WhisperLang::Malay => "ms".to_string(),
            WhisperLang::Malayalam => "ml".to_string(),
            WhisperLang::Maltese => "mt".to_string(),
            WhisperLang::Maori => "mi".to_string(),
            WhisperLang::Marathi => "mr".to_string(),
            WhisperLang::Mongolian => "mn".to_string(),
            WhisperLang::Nepali => "ne".to_string(),
            WhisperLang::Norwegian => "no".to_string(),
            WhisperLang::Nynorsk => "nn".to_string(),
            WhisperLang::Occitan => "oc".to_string(),
            WhisperLang::Pashto => "ps".to_string(),
            WhisperLang::Persian => "fa".to_string(),
            WhisperLang::Polish => "pl".to_string(),
            WhisperLang::Portuguese => "pt".to_string(),
            WhisperLang::Punjabi => "pa".to_string(),
            WhisperLang::Romanian => "ro".to_string(),
            WhisperLang::Russian => "ru".to_string(),
            WhisperLang::Sanskrit => "sa".to_string(),
            WhisperLang::Serbian => "sr".to_string(),
            WhisperLang::Shona => "sn".to_string(),
            WhisperLang::Sindhi => "sd".to_string(),
            WhisperLang::Sinhala => "si".to_string(),
            WhisperLang::Slovak => "sk".to_string(),
            WhisperLang::Slovenian => "sl".to_string(),
            WhisperLang::Somali => "so".to_string(),
            WhisperLang::Spanish => "es".to_string(),
            WhisperLang::Sundanese => "su".to_string(),
            WhisperLang::Swahili => "sw".to_string(),
            WhisperLang::Swedish => "sv".to_string(),
            WhisperLang::Tagalog => "tl".to_string(),
            WhisperLang::Tajik => "tg".to_string(),
            WhisperLang::Tamil => "ta".to_string(),
            WhisperLang::Tatar => "tt".to_string(),
            WhisperLang::Telugu => "te".to_string(),
            WhisperLang::Thai => "th".to_string(),
            WhisperLang::Tibetan => "bo".to_string(),
            WhisperLang::Turkish => "tr".to_string(),
            WhisperLang::Turkmen => "tk".to_string(),
            WhisperLang::Ukrainian => "uk".to_string(),
            WhisperLang::Urdu => "ur".to_string(),
            WhisperLang::Uzbek => "uz".to_string(),
            WhisperLang::Vietnamese => "vi".to_string(),
            WhisperLang::Welsh => "cy".to_string(),
            WhisperLang::Yiddish => "yi".to_string(),
            WhisperLang::Yoruba => "yo".to_string(),
        }
    }
}

impl From<&str> for WhisperLang {
    fn from(lang: &str) -> Self {
        match lang {
            "auto" => WhisperLang::Auto,
            "af" => WhisperLang::Afrikaans,
            "am" => WhisperLang::Amharic,
            "ar" => WhisperLang::Arabic,
            "as" => WhisperLang::Assamese,
            "az" => WhisperLang::Azerbaijani,
            "ba" => WhisperLang::Bashkir,
            "be" => WhisperLang::Belarusian,
            "bn" => WhisperLang::Bengali,
            "bs" => WhisperLang::Bosnian,
            "br" => WhisperLang::Breton,
            "bg" => WhisperLang::Bulgarian,
            "my" => WhisperLang::Burmese,
            "ca" => WhisperLang::Catalan,
            "zh" => WhisperLang::Chinese,
            "hr" => WhisperLang::Croatian,
            "cs" => WhisperLang::Czech,
            "da" => WhisperLang::Danish,
            "nl" => WhisperLang::Dutch,
            "en" => WhisperLang::English,
            "et" => WhisperLang::Estonian,
            "fo" => WhisperLang::Faroese,
            "fi" => WhisperLang::Finnish,
            "fr" => WhisperLang::French,
            "gl" => WhisperLang::Galician,
            "ka" => WhisperLang::Georgian,
            "de" => WhisperLang::German,
            "el" => WhisperLang::Greek,
            "gu" => WhisperLang::Gujarati,
            "ht" => WhisperLang::HaitianCreole,
            "ha" => WhisperLang::Hausa,
            "haw" => WhisperLang::Hawaiian,
            "he" => WhisperLang::Hebrew,
            "hi" => WhisperLang::Hindi,
            "hu" => WhisperLang::Hungarian,
            "is" => WhisperLang::Icelandic,
            "id" => WhisperLang::Indonesian,
            "it" => WhisperLang::Italian,
            "ja" => WhisperLang::Japanese,
            "jw" => WhisperLang::Javanese,
            "kn" => WhisperLang::Kannada,
            "kk" => WhisperLang::Kazakh,
            "km" => WhisperLang::Khmer,
            "ko" => WhisperLang::Korean,
            "lo" => WhisperLang::Lao,
            "la" => WhisperLang::Latin,
            "lv" => WhisperLang::Latvian,
            "ln" => WhisperLang::Lingala,
            "lt" => WhisperLang::Lithuanian,
            "lb" => WhisperLang::Luxembourgish,
            "mk" => WhisperLang::Macedonian,
            "mg" => WhisperLang::Malagasy,
            "ms" => WhisperLang::Malay,
            "ml" => WhisperLang::Malayalam,
            "mt" => WhisperLang::Maltese,
            "mi" => WhisperLang::Maori,
            "mr" => WhisperLang::Marathi,
            "mn" => WhisperLang::Mongolian,
            "ne" => WhisperLang::Nepali,
            "no" => WhisperLang::Norwegian,
            "nn" => WhisperLang::Nynorsk,
            "oc" => WhisperLang::Occitan,
            "ps" => WhisperLang::Pashto,
            "fa" => WhisperLang::Persian,
            "pl" => WhisperLang::Polish,
            "pt" => WhisperLang::Portuguese,
            "pa" => WhisperLang::Punjabi,
            "ro" => WhisperLang::Romanian,
            "ru" => WhisperLang::Russian,
            "sa" => WhisperLang::Sanskrit,
            "sr" => WhisperLang::Serbian,
            "sn" => WhisperLang::Shona,
            "sd" => WhisperLang::Sindhi,
            "si" => WhisperLang::Sinhala,
            "sk" => WhisperLang::Slovak,
            "sl" => WhisperLang::Slovenian,
            "so" => WhisperLang::Somali,
            "es" => WhisperLang::Spanish,
            "su" => WhisperLang::Sundanese,
            "sw" => WhisperLang::Swahili,
            "sv" => WhisperLang::Swedish,
            "tl" => WhisperLang::Tagalog,
            "tg" => WhisperLang::Tajik,
            "ta" => WhisperLang::Tamil,
            "tt" => WhisperLang::Tatar,
            "te" => WhisperLang::Telugu,
            "th" => WhisperLang::Thai,
            "bo" => WhisperLang::Tibetan,
            "tr" => WhisperLang::Turkish,
            "tk" => WhisperLang::Turkmen,
            "uk" => WhisperLang::Ukrainian,
            "ur" => WhisperLang::Urdu,
            "uz" => WhisperLang::Uzbek,
            "vi" => WhisperLang::Vietnamese,
            "cy" => WhisperLang::Welsh,
            "yi" => WhisperLang::Yiddish,
            "yo" => WhisperLang::Yoruba,
            _ => WhisperLang::Auto,
        }
    }
}

impl Default for WhisperLang {
    fn default() -> Self {
        WhisperLang::Auto
    }
}

impl WhisperLang {
    pub fn all_languages() -> Vec<(Self, &'static str, &'static str)> {
        vec![
            (WhisperLang::Auto, "auto", "Auto detect"),
            (WhisperLang::Afrikaans, "af", "Afrikaans"),
            (WhisperLang::Amharic, "am", "Amharic"),
            (WhisperLang::Arabic, "ar", "Arabic"),
            (WhisperLang::Assamese, "as", "Assamese"),
            (WhisperLang::Azerbaijani, "az", "Azerbaijani"),
            (WhisperLang::Bashkir, "ba", "Bashkir"),
            (WhisperLang::Belarusian, "be", "Belarusian"),
            (WhisperLang::Bengali, "bn", "Bengali"),
            (WhisperLang::Bosnian, "bs", "Bosnian"),
            (WhisperLang::Breton, "br", "Breton"),
            (WhisperLang::Bulgarian, "bg", "Bulgarian"),
            (WhisperLang::Burmese, "my", "Burmese"),
            (WhisperLang::Catalan, "ca", "Catalan"),
            (WhisperLang::Chinese, "zh", "Chinese"),
            (WhisperLang::Croatian, "hr", "Croatian"),
            (WhisperLang::Czech, "cs", "Czech"),
            (WhisperLang::Danish, "da", "Danish"),
            (WhisperLang::Dutch, "nl", "Dutch"),
            (WhisperLang::English, "en", "English"),
            (WhisperLang::Estonian, "et", "Estonian"),
            (WhisperLang::Faroese, "fo", "Faroese"),
            (WhisperLang::Finnish, "fi", "Finnish"),
            (WhisperLang::French, "fr", "French"),
            (WhisperLang::Galician, "gl", "Galician"),
            (WhisperLang::Georgian, "ka", "Georgian"),
            (WhisperLang::German, "de", "German"),
            (WhisperLang::Greek, "el", "Greek"),
            (WhisperLang::Gujarati, "gu", "Gujarati"),
            (WhisperLang::HaitianCreole, "ht", "Haitian Creole"),
            (WhisperLang::Hausa, "ha", "Hausa"),
            (WhisperLang::Hawaiian, "haw", "Hawaiian"),
            (WhisperLang::Hebrew, "he", "Hebrew"),
            (WhisperLang::Hindi, "hi", "Hindi"),
            (WhisperLang::Hungarian, "hu", "Hungarian"),
            (WhisperLang::Icelandic, "is", "Icelandic"),
            (WhisperLang::Indonesian, "id", "Indonesian"),
            (WhisperLang::Italian, "it", "Italian"),
            (WhisperLang::Japanese, "ja", "Japanese"),
            (WhisperLang::Javanese, "jw", "Javanese"),
            (WhisperLang::Kannada, "kn", "Kannada"),
            (WhisperLang::Kazakh, "kk", "Kazakh"),
            (WhisperLang::Khmer, "km", "Khmer"),
            (WhisperLang::Korean, "ko", "Korean"),
            (WhisperLang::Lao, "lo", "Lao"),
            (WhisperLang::Latin, "la", "Latin"),
            (WhisperLang::Latvian, "lv", "Latvian"),
            (WhisperLang::Lingala, "ln", "Lingala"),
            (WhisperLang::Lithuanian, "lt", "Lithuanian"),
            (WhisperLang::Luxembourgish, "lb", "Luxembourgish"),
            (WhisperLang::Macedonian, "mk", "Macedonian"),
            (WhisperLang::Malagasy, "mg", "Malagasy"),
            (WhisperLang::Malay, "ms", "Malay"),
            (WhisperLang::Malayalam, "ml", "Malayalam"),
            (WhisperLang::Maltese, "mt", "Maltese"),
            (WhisperLang::Maori, "mi", "Maori"),
            (WhisperLang::Marathi, "mr", "Marathi"),
            (WhisperLang::Mongolian, "mn", "Mongolian"),
            (WhisperLang::Nepali, "ne", "Nepali"),
            (WhisperLang::Norwegian, "no", "Norwegian"),
            (WhisperLang::Nynorsk, "nn", "Nynorsk"),
            (WhisperLang::Occitan, "oc", "Occitan"),
            (WhisperLang::Pashto, "ps", "Pashto"),
            (WhisperLang::Persian, "fa", "Persian"),
            (WhisperLang::Polish, "pl", "Polish"),
            (WhisperLang::Portuguese, "pt", "Portuguese"),
            (WhisperLang::Punjabi, "pa", "Punjabi"),
            (WhisperLang::Romanian, "ro", "Romanian"),
            (WhisperLang::Russian, "ru", "Russian"),
            (WhisperLang::Sanskrit, "sa", "Sanskrit"),
            (WhisperLang::Serbian, "sr", "Serbian"),
            (WhisperLang::Shona, "sn", "Shona"),
            (WhisperLang::Sindhi, "sd", "Sindhi"),
            (WhisperLang::Sinhala, "si", "Sinhala"),
            (WhisperLang::Slovak, "sk", "Slovak"),
            (WhisperLang::Slovenian, "sl", "Slovenian"),
            (WhisperLang::Somali, "so", "Somali"),
            (WhisperLang::Spanish, "es", "Spanish"),
            (WhisperLang::Sundanese, "su", "Sundanese"),
            (WhisperLang::Swahili, "sw", "Swahili"),
            (WhisperLang::Swedish, "sv", "Swedish"),
            (WhisperLang::Tagalog, "tl", "Tagalog"),
            (WhisperLang::Tajik, "tg", "Tajik"),
            (WhisperLang::Tamil, "ta", "Tamil"),
            (WhisperLang::Tatar, "tt", "Tatar"),
            (WhisperLang::Telugu, "te", "Telugu"),
            (WhisperLang::Thai, "th", "Thai"),
            (WhisperLang::Tibetan, "bo", "Tibetan"),
            (WhisperLang::Turkish, "tr", "Turkish"),
            (WhisperLang::Turkmen, "tk", "Turkmen"),
            (WhisperLang::Ukrainian, "uk", "Ukrainian"),
            (WhisperLang::Urdu, "ur", "Urdu"),
            (WhisperLang::Uzbek, "uz", "Uzbek"),
            (WhisperLang::Vietnamese, "vi", "Vietnamese"),
            (WhisperLang::Welsh, "cy", "Welsh"),
            (WhisperLang::Yiddish, "yi", "Yiddish"),
            (WhisperLang::Yoruba, "yo", "Yoruba"),
        ]
    }

    // e.g. "Chinese" -> "zh", "English" -> "en"
    pub fn get_code_from_long_name(long_name: &str) -> Option<String> {
        let lang = match long_name.to_lowercase().as_str() {
            "auto" | "auto detect" => Some(WhisperLang::Auto),
            "afrikaans" => Some(WhisperLang::Afrikaans),
            "amharic" => Some(WhisperLang::Amharic),
            "arabic" => Some(WhisperLang::Arabic),
            "assamese" => Some(WhisperLang::Assamese),
            "azerbaijani" => Some(WhisperLang::Azerbaijani),
            "bashkir" => Some(WhisperLang::Bashkir),
            "belarusian" => Some(WhisperLang::Belarusian),
            "bengali" => Some(WhisperLang::Bengali),
            "bosnian" => Some(WhisperLang::Bosnian),
            "breton" => Some(WhisperLang::Breton),
            "bulgarian" => Some(WhisperLang::Bulgarian),
            "burmese" => Some(WhisperLang::Burmese),
            "catalan" => Some(WhisperLang::Catalan),
            "chinese" => Some(WhisperLang::Chinese),
            "croatian" => Some(WhisperLang::Croatian),
            "czech" => Some(WhisperLang::Czech),
            "danish" => Some(WhisperLang::Danish),
            "dutch" => Some(WhisperLang::Dutch),
            "english" => Some(WhisperLang::English),
            "estonian" => Some(WhisperLang::Estonian),
            "faroese" => Some(WhisperLang::Faroese),
            "finnish" => Some(WhisperLang::Finnish),
            "french" => Some(WhisperLang::French),
            "galician" => Some(WhisperLang::Galician),
            "georgian" => Some(WhisperLang::Georgian),
            "german" => Some(WhisperLang::German),
            "greek" => Some(WhisperLang::Greek),
            "gujarati" => Some(WhisperLang::Gujarati),
            "haitian creole" | "haitiancreole" => Some(WhisperLang::HaitianCreole),
            "hausa" => Some(WhisperLang::Hausa),
            "hawaiian" => Some(WhisperLang::Hawaiian),
            "hebrew" => Some(WhisperLang::Hebrew),
            "hindi" => Some(WhisperLang::Hindi),
            "hungarian" => Some(WhisperLang::Hungarian),
            "icelandic" => Some(WhisperLang::Icelandic),
            "indonesian" => Some(WhisperLang::Indonesian),
            "italian" => Some(WhisperLang::Italian),
            "japanese" => Some(WhisperLang::Japanese),
            "javanese" => Some(WhisperLang::Javanese),
            "kannada" => Some(WhisperLang::Kannada),
            "kazakh" => Some(WhisperLang::Kazakh),
            "khmer" => Some(WhisperLang::Khmer),
            "korean" => Some(WhisperLang::Korean),
            "lao" => Some(WhisperLang::Lao),
            "latvian" => Some(WhisperLang::Latvian),
            "latin" => Some(WhisperLang::Latin),
            "lingala" => Some(WhisperLang::Lingala),
            "lithuanian" => Some(WhisperLang::Lithuanian),
            "luxembourgish" => Some(WhisperLang::Luxembourgish),
            "macedonian" => Some(WhisperLang::Macedonian),
            "malagasy" => Some(WhisperLang::Malagasy),
            "malay" => Some(WhisperLang::Malay),
            "malayalam" => Some(WhisperLang::Malayalam),
            "maltese" => Some(WhisperLang::Maltese),
            "maori" => Some(WhisperLang::Maori),
            "marathi" => Some(WhisperLang::Marathi),
            "mongolian" => Some(WhisperLang::Mongolian),
            "nepali" => Some(WhisperLang::Nepali),
            "norwegian" => Some(WhisperLang::Norwegian),
            "nynorsk" => Some(WhisperLang::Nynorsk),
            "occitan" => Some(WhisperLang::Occitan),
            "pashto" => Some(WhisperLang::Pashto),
            "persian" => Some(WhisperLang::Persian),
            "polish" => Some(WhisperLang::Polish),
            "portuguese" => Some(WhisperLang::Portuguese),
            "punjabi" => Some(WhisperLang::Punjabi),
            "romanian" => Some(WhisperLang::Romanian),
            "russian" => Some(WhisperLang::Russian),
            "sanskrit" => Some(WhisperLang::Sanskrit),
            "serbian" => Some(WhisperLang::Serbian),
            "shona" => Some(WhisperLang::Shona),
            "sindhi" => Some(WhisperLang::Sindhi),
            "sinhala" => Some(WhisperLang::Sinhala),
            "slovak" => Some(WhisperLang::Slovak),
            "slovenian" => Some(WhisperLang::Slovenian),
            "somali" => Some(WhisperLang::Somali),
            "spanish" => Some(WhisperLang::Spanish),
            "sundanese" => Some(WhisperLang::Sundanese),
            "swahili" => Some(WhisperLang::Swahili),
            "swedish" => Some(WhisperLang::Swedish),
            "tagalog" => Some(WhisperLang::Tagalog),
            "tajik" => Some(WhisperLang::Tajik),
            "tamil" => Some(WhisperLang::Tamil),
            "tatar" => Some(WhisperLang::Tatar),
            "telugu" => Some(WhisperLang::Telugu),
            "thai" => Some(WhisperLang::Thai),
            "tibetan" => Some(WhisperLang::Tibetan),
            "turkish" => Some(WhisperLang::Turkish),
            "turkmen" => Some(WhisperLang::Turkmen),
            "ukrainian" => Some(WhisperLang::Ukrainian),
            "urdu" => Some(WhisperLang::Urdu),
            "uzbek" => Some(WhisperLang::Uzbek),
            "vietnamese" => Some(WhisperLang::Vietnamese),
            "welsh" => Some(WhisperLang::Welsh),
            "yiddish" => Some(WhisperLang::Yiddish),
            "yoruba" => Some(WhisperLang::Yoruba),
            _ => None,
        };

        lang.map(|l| l.to_string())
    }

    pub fn from_long_name(long_name: &str) -> Option<Self> {
        match long_name.to_lowercase().as_str() {
            "auto" | "auto detect" => Some(WhisperLang::Auto),
            "afrikaans" => Some(WhisperLang::Afrikaans),
            "amharic" => Some(WhisperLang::Amharic),
            "arabic" => Some(WhisperLang::Arabic),
            "assamese" => Some(WhisperLang::Assamese),
            "azerbaijani" => Some(WhisperLang::Azerbaijani),
            "bashkir" => Some(WhisperLang::Bashkir),
            "belarusian" => Some(WhisperLang::Belarusian),
            "bengali" => Some(WhisperLang::Bengali),
            "bosnian" => Some(WhisperLang::Bosnian),
            "breton" => Some(WhisperLang::Breton),
            "bulgarian" => Some(WhisperLang::Bulgarian),
            "burmese" => Some(WhisperLang::Burmese),
            "catalan" => Some(WhisperLang::Catalan),
            "chinese" => Some(WhisperLang::Chinese),
            "croatian" => Some(WhisperLang::Croatian),
            "czech" => Some(WhisperLang::Czech),
            "danish" => Some(WhisperLang::Danish),
            "dutch" => Some(WhisperLang::Dutch),
            "english" => Some(WhisperLang::English),
            "estonian" => Some(WhisperLang::Estonian),
            "faroese" => Some(WhisperLang::Faroese),
            "finnish" => Some(WhisperLang::Finnish),
            "french" => Some(WhisperLang::French),
            "galician" => Some(WhisperLang::Galician),
            "georgian" => Some(WhisperLang::Georgian),
            "german" => Some(WhisperLang::German),
            "greek" => Some(WhisperLang::Greek),
            "gujarati" => Some(WhisperLang::Gujarati),
            "haitian creole" | "haitiancreole" => Some(WhisperLang::HaitianCreole),
            "hausa" => Some(WhisperLang::Hausa),
            "hawaiian" => Some(WhisperLang::Hawaiian),
            "hebrew" => Some(WhisperLang::Hebrew),
            "hindi" => Some(WhisperLang::Hindi),
            "hungarian" => Some(WhisperLang::Hungarian),
            "icelandic" => Some(WhisperLang::Icelandic),
            "indonesian" => Some(WhisperLang::Indonesian),
            "italian" => Some(WhisperLang::Italian),
            "japanese" => Some(WhisperLang::Japanese),
            "javanese" => Some(WhisperLang::Javanese),
            "kannada" => Some(WhisperLang::Kannada),
            "kazakh" => Some(WhisperLang::Kazakh),
            "khmer" => Some(WhisperLang::Khmer),
            "korean" => Some(WhisperLang::Korean),
            "lao" => Some(WhisperLang::Lao),
            "latvian" => Some(WhisperLang::Latvian),
            "latin" => Some(WhisperLang::Latin),
            "lingala" => Some(WhisperLang::Lingala),
            "lithuanian" => Some(WhisperLang::Lithuanian),
            "luxembourgish" => Some(WhisperLang::Luxembourgish),
            "macedonian" => Some(WhisperLang::Macedonian),
            "malagasy" => Some(WhisperLang::Malagasy),
            "malay" => Some(WhisperLang::Malay),
            "malayalam" => Some(WhisperLang::Malayalam),
            "maltese" => Some(WhisperLang::Maltese),
            "maori" => Some(WhisperLang::Maori),
            "marathi" => Some(WhisperLang::Marathi),
            "mongolian" => Some(WhisperLang::Mongolian),
            "nepali" => Some(WhisperLang::Nepali),
            "norwegian" => Some(WhisperLang::Norwegian),
            "nynorsk" => Some(WhisperLang::Nynorsk),
            "occitan" => Some(WhisperLang::Occitan),
            "pashto" => Some(WhisperLang::Pashto),
            "persian" => Some(WhisperLang::Persian),
            "polish" => Some(WhisperLang::Polish),
            "portuguese" => Some(WhisperLang::Portuguese),
            "punjabi" => Some(WhisperLang::Punjabi),
            "romanian" => Some(WhisperLang::Romanian),
            "russian" => Some(WhisperLang::Russian),
            "sanskrit" => Some(WhisperLang::Sanskrit),
            "serbian" => Some(WhisperLang::Serbian),
            "shona" => Some(WhisperLang::Shona),
            "sindhi" => Some(WhisperLang::Sindhi),
            "sinhala" => Some(WhisperLang::Sinhala),
            "slovak" => Some(WhisperLang::Slovak),
            "slovenian" => Some(WhisperLang::Slovenian),
            "somali" => Some(WhisperLang::Somali),
            "spanish" => Some(WhisperLang::Spanish),
            "sundanese" => Some(WhisperLang::Sundanese),
            "swahili" => Some(WhisperLang::Swahili),
            "swedish" => Some(WhisperLang::Swedish),
            "tagalog" => Some(WhisperLang::Tagalog),
            "tajik" => Some(WhisperLang::Tajik),
            "tamil" => Some(WhisperLang::Tamil),
            "tatar" => Some(WhisperLang::Tatar),
            "telugu" => Some(WhisperLang::Telugu),
            "thai" => Some(WhisperLang::Thai),
            "tibetan" => Some(WhisperLang::Tibetan),
            "turkish" => Some(WhisperLang::Turkish),
            "turkmen" => Some(WhisperLang::Turkmen),
            "ukrainian" => Some(WhisperLang::Ukrainian),
            "urdu" => Some(WhisperLang::Urdu),
            "uzbek" => Some(WhisperLang::Uzbek),
            "vietnamese" => Some(WhisperLang::Vietnamese),
            "welsh" => Some(WhisperLang::Welsh),
            "yiddish" => Some(WhisperLang::Yiddish),
            "yoruba" => Some(WhisperLang::Yoruba),
            _ => None,
        }
    }
}
